development:
  adapter: mysql2
  database: radio_ego
  username: root
  password: texmex
  host: localhost
  encoding: utf8
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: radio_ego_test
  username: root
  password: texmex
  host: localhost
  encoding: utf8
  socket: /tmp/mysql.sock